const express = require('express');
const router = express.Router();
const Match = require('../models/Match');

router.get('/seedFixtures', async (req, res) => {
    try {
        await Match.deleteMany(); // optional: clear old data
        const fixtures = [
            // Football Fixtures
            {   //match-1
                sport: 'football',
                category: 'U10 Boys',
                matchNumber: 1,
                teamA: 'Sabreen Utd (VC)',
                teamB: 'Al Aqsa warriors (MA)',
                ground: 'Ground 1',
                isAutoGenerated: false,
            },
            {   //match-2
                sport: 'football',
                category: 'U10 Boys',
                matchNumber: 2,
                teamA: 'Little Strikers (CO)',
                teamB: 'Unison Cubs (HN)',
                ground: 'Ground 2',
                isAutoGenerated: false,
            },
            {
                //match-3
                sport: 'football',
                category: 'U10 Boys',
                matchNumber: 3,
                teamA: 'Blasters (BG)',
                teamB: null,
                ground: 'Ground 1',
                isAutoGenerated: true,
            },
            {
                //match-4
                sport: 'football',
                category: 'U10 Boys',
                matchNumber: 4,
                teamA: 'Inthifada FC (MA)',
                teamB: null,
                ground: 'Ground 1',
                isAutoGenerated: true,
            },
            {
                //match-5
                sport: 'football',
                category: 'U10 Boys',
                matchNumber: 5,
                teamA: null,
                teamB: null,
                ground: 'Ground 1',
                isAutoGenerated: true,
            },
            {
                //match-1
                sport: 'football',
                category: 'U13 Boys',
                matchNumber: 1,
                teamA: 'Goal Hunters (CO)',
                teamB: 'Dynamos (BG)',
                ground: 'Ground 1',
                isAutoGenerated: false,
            },
            {
                //match-2
                sport: 'football',
                category: 'U13 Boys',
                matchNumber: 2,
                teamA: 'Koramangala M (KO)',
                teamB: 'Qudus FC (MIX)',
                ground: 'Ground 2',
                isAutoGenerated: false,
            },
            {
                //match-3
                sport: 'football',
                category: 'U13 Boys',
                matchNumber: 3,
                teamA: 'Al Iqwan FC (MA)',
                teamB: 'Nagharbhavi (NIC)',
                ground: 'Ground 1',
                isAutoGenerated: false,
            },
            {
                //match-4
                sport: 'football',
                category: 'U13 Boys',
                matchNumber: 4,
                teamA: 'Unison Lions (HN)',
                teamB: null,
                ground: 'Ground 2',
                isAutoGenerated: true,
            },
            {
                //match-5
                sport: 'football',
                category: 'U13 Boys',
                matchNumber: 5,
                teamA: null,
                teamB: null,
                ground: 'Ground 2',
                isAutoGenerated: true,
            },
            {
                //match-6 - final
                sport: 'football',
                category: 'U13 Boys',
                matchNumber: 6,
                teamA: null,
                teamB: null,
                ground: 'Ground 2',
                isAutoGenerated: true,
            },
            {
                //match-1 - 
                sport: 'football',
                category: 'Gents',
                matchNumber: 1,
                teamA: 'Handala FC (SUK)',
                teamB: 'Edifis FC (MA)',
                ground: 'Ground 2',
                isAutoGenerated: false,
            },
            {
                //match-2 - 
                sport: 'football',
                category: 'Gents',
                matchNumber: 2,
                teamA: 'Nagharbhavi Legends (NIC)',
                teamB: 'BG City Amigos (BG)',
                ground: 'Ground 2',
                isAutoGenerated: false,
            },
            {
                //match-3 - 
                sport: 'football',
                category: 'Gents',
                matchNumber: 3,
                teamA: 'Koramangala FC (KO)',
                teamB: null,
                ground: 'Ground 2',
                isAutoGenerated: true,
            },
            {
                //match-4 - Final
                sport: 'football',
                category: 'Gents',
                matchNumber: 4,
                teamA: null,
                teamB: null,
                ground: 'Ground 2',
                isAutoGenerated: true,
            }
        ];
        await Match.insertMany(fixtures);
        res.send('Fixtures seeded successfully!');
    } catch (error) {
        console.error('Seeding error:', error);
        res.status(500).send('Error seeding fixtures');
    }
});

module.exports = router;