const mongoose = require('mongoose');

const matchSchema = new mongoose.Schema({
  sport: String,
  category: String,
  matchNumber: Number,
  teamA: String,
  teamB: String,
  ground: String,
  result: {
    teamA: Number,
    teamB: Number,
    winner: String
  },
  isAutoGenerated: { type: Boolean, default: false }
});

module.exports = mongoose.model('Match', matchSchema);
